---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yml
  - statefulset.yml

configMapGenerator:
  - name: minecraft-server
    options:
      labels:
        app.kubernetes.io/name: minecraft
        app.kubernetes.io/component: server
    literals:
      - MINECRAFT_MOTD=Grimson by Webhippie

secretGenerator:
  - name: minecraft-server
    options:
      labels:
        app.kubernetes.io/name: minecraft
        app.kubernetes.io/component: server
    literals: []

images:
  - name: minecraft-server
    newName: quay.io/crafthippie/grimson
    newTag: 2.0.33@sha256:a09af442a8f559600b7c6ffe12ef5f17e338497173fe3250d0b35dc9065d18a5

...
